services:
  acontext-server-pg:
    image: postgres:16
    restart: unless-stopped
    container_name: acontext-server-pg
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - '5432:5432'
    volumes:
      - ${DATABASE_LOCATION}:/var/lib/postgresql/data
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 30s
      timeout: 5s
      retries: 5
  
  acontext-server-redis:
    image: redis:7.4
    restart: unless-stopped
    container_name: acontext-server-redis
    ports:
      - "6379:6379"
    volumes:
      - ${REDIS_LOCATION}:/data
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 5

  acontext-server-rabbitmq:
    image: rabbitmq:3
    restart: unless-stopped
    container_name: acontext-server-rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - ${RABBITMQ_LOCATION}:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  acontext-server-pg:
    driver: local
  acontext-server-redis:
    driver: local
  acontext-server-rabbitmq:
    driver: local